function injectBlockly() {
	// var toolbox = document.getElementById("toolbox");

	const options = { 
		toolbox : graphicsToolbox(), 
		collapse : true, 
		comments : true, 
		disable : true, 
		maxBlocks : Infinity, 
		trashcan : true, 
		horizontalLayout : false, 
		toolboxPosition : 'start', 
		css : true, 
		media : '../script/blockly/msg/media/', 
		rtl : false, 
		scrollbars : true, 
		sounds : true, 
		oneBasedIndex : true
	};
	
	/* Inject your workspace */ 
	const workspace = Blockly.inject('blocklyDiv', options);
	
	/* Load Workspace Blocks from XML to workspace */
	const workspaceBlocks = document.getElementById("workspaceBlocks"); 
	Blockly.Xml.domToWorkspace(workspaceBlocks, workspace);

	function myUpdateFunction(event) {
		let source = `// graphics setup
const canvas = document.getElementById("canvas");
const graphics = canvas.getContext("2d");
graphics.setTransform(1, 0, 0, 1, 0, 0);
graphics.clearRect(0, 0, 500, 500);
graphics.fillStyle = "#F8F8F8";
graphics.fillRect(0, 0, 500, 500);

// JavaScript generated by Blockly for HTML5 canvas
`;
		source = source + Blockly.JavaScript.workspaceToCode(workspace);
		document.getElementById('textarea').value = source;
		const block = Function(source);
		block();
	}
	
	workspace.addChangeListener(myUpdateFunction);
}
